import { afcDate } from './AfcReportHeader';
import { afcAlign, afcColumns, afcValue } from './AfcReportGrid';

export default function AfcReportPrintView({ data }) {
  const header = data?.header || {};
  const rows = data?.rows || [];
  const generatedAt = data?.generatedAt ? new Date(data.generatedAt) : new Date();

  return (
    <div className="afc-print-root">
      <div className="afc-print-header">
        <h1>DUGAR FINANCE</h1>
        <h2>AFC REPORT</h2>
        <div className="afc-print-meta">
          <span>Loan Number: {header.loanNumber || ''}</span>
          <span>Customer Name: {header.customerName || ''}</span>
          <span>Product Type: {header.productType || ''}</span>
          <span>As On Date: {afcDate(header.asOnDate)}</span>
          <span>Generated By: {data?.generatedBy || ''}</span>
          <span>Generated Date: {generatedAt.toLocaleDateString('en-GB')}</span>
        </div>
      </div>
      <table className="afc-print-table">
        <thead>
          <tr>
            {afcColumns.map(([field, label, type]) => (
              <th key={field} className={afcAlign(type).replace('text-', '')}>{label}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={`${row.serialNumber}-${row.dueDate}`}>
              {afcColumns.map(([field, , type]) => (
                <td key={field} className={afcAlign(type).replace('text-', '')}>{afcValue(row, field, type)}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
